name: Build Application

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo '${{ secrets.ENV }}' >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm install
      - name: Npm build
        run: npm run build
      - name: Npm test
        run: npm run test
